--------------------------------------------------------------------------------
-- Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.5
--  \   \         Application : xaw2vhdl
--  /   /         Filename : hdllab_pll.vhd
-- /___/   /\     Timestamp : 07/13/2015 11:12:37
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/alexs/LEHRE/IES/HDL-Lab/hdllab/src/test/syn/hdllab/ipcore_dir/./hdllab_pll.xaw /home/alexs/LEHRE/IES/HDL-Lab/hdllab/src/test/syn/hdllab/ipcore_dir/./hdllab_pll
--Design Name: hdllab_pll
--Device: xc5vfx70t-1ff1136
--
-- Module hdllab_pll
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: Synplify
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.141 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity hdllab_pll is
   port ( CLKIN1_N_IN  : in    std_logic; 
          CLKIN1_P_IN  : in    std_logic; 
          RST_IN       : in    std_logic; 
          CLKFBOUT_OUT : out   std_logic; 
          CLKOUT0_OUT  : out   std_logic; 
          LOCKED_OUT   : out   std_logic);
end hdllab_pll;

architecture BEHAVIORAL of hdllab_pll is
   signal CLKFBIN_IN     : std_logic;
   signal CLKFBOUT_BUF   : std_logic;
   signal CLKIN1_IBUFGDS : std_logic;
   signal CLKOUT0_BUF    : std_logic;
   signal GND_BIT        : std_logic;
   signal GND_BUS_5      : std_logic_vector (4 downto 0);
   signal GND_BUS_16     : std_logic_vector (15 downto 0);
   signal VCC_BIT        : std_logic;
begin
   GND_BIT <= '0';
   GND_BUS_5(4 downto 0) <= "00000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   CLKFBOUT_OUT <= CLKFBIN_IN;
   CLKFBOUT_BUFG_INST : BUFG
      port map (I=>CLKFBOUT_BUF,
                O=>CLKFBIN_IN);
   
   CLKIN1_IBUFGDS_INST : IBUFGDS
      port map (I=>CLKIN1_P_IN,
                IB=>CLKIN1_N_IN,
                O=>CLKIN1_IBUFGDS);
   
   CLKOUT0_BUFG_INST : BUFG
      port map (I=>CLKOUT0_BUF,
                O=>CLKOUT0_OUT);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 5.000,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 3,
            CLKOUT0_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            COMPENSATION => "SYSTEM_SYNCHRONOUS",
            DIVCLK_DIVIDE => 2,
            CLKFBOUT_MULT => 6,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.005000)
      port map (CLKFBIN=>CLKFBIN_IN,
                CLKINSEL=>VCC_BIT,
                CLKIN1=>CLKIN1_IBUFGDS,
                CLKIN2=>GND_BIT,
                DADDR(4 downto 0)=>GND_BUS_5(4 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                REL=>GND_BIT,
                RST=>RST_IN,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_BUF,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>open,
                CLKOUT2=>open,
                CLKOUT3=>open,
                CLKOUT4=>open,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>LOCKED_OUT);
   
end BEHAVIORAL;


